### PR TITLE
Update the docstrings of the dataikuapi.dss.project classes and methods to follow guidelines

### PR DESCRIPTION
**Pull request by clemencebic**
Here is the enhancement of docstrings in the dataikuapi.dss.project section to follow the guidelines that have been updated here: https://analytics.dataiku.com/projects/RDWIKI/wiki/239/Coding%20rules%20for%20public%20APIs#the-reference-doc-1.
Feel free to also review and add rules in the guidelines.

### CODE REVIEW

**Review by FlorentDev64 — CHANGES_REQUESTED** [review]
I tried to make as many suggestions as possible, but some where not feasible because they were to0 far from your modifications.

I removed the duplication of the reference of the :class: and put them in the :rtype:.
I think we should indicate in the documentation when a value has a defult value (and which one).
Some functions does not have all parameters documened . 

So there are still modifications to do to uniform the documentation. 
I think we should have the description of the function, and then the usage example.

You'll find a list of function where some documentation should be fixed
- delete: missing parameter kwargs (MP), default value missing (DVM)
- duplicate: DVM
- get_timeline: DVM
- list_datasets: DVM
- create_upload_dataset: DVM
- create_fslike_dataset: Document is missing (DM)
- create_sql_table_dataset: DM
- list_streaming_endpoints: DVM
- create_kafka_streaming_endpoint: DM
- create_httpse_streaming_endpoint: DM
- create_prediction_ml_task: DVM
- create_clustering_ml_task: DVM
- create_managed_folder: MP, DVM
- get_jobs: MP
- start_job_and_wait: DVM
- new_job: DVM
- list_jupyter_notebooks: DVM
- create_jupyter_notebook: :rtype: refer to class rather than ~class
- list-continous_activities: DVM
- update_variables: DVM
- create_api_service: :returns: should be changed and :rtype: should  refer to class rather than ~class
- get_api_service: :rtype: should  refer to class rather than ~class
- export_bundle: I think we miss a code example
- download_exported_bundle_archive_to_file: need code sample ?
- list_scenation: DVM
- list_recipes: DVM
- new_recipe: missing :returns:
- get_flow: missing :returns:
- list_macros: DVM
- list_sql_tables: MP (all)
- list_hive_tables: MP, and code sample ?
- get_app_manifest: DM
- setup_mlflow: DVM
- get_mlflow_extension: missing :rtype:
- list_code_studios: DVM
- add_hive_table: DM
- add_sql_table: DM
- set_k8s_cluster: DVM
- set_cluster: DVM
- add°exposed_object: MP (all)
- with_refresh_metastore: MP
- with°output: DVM
- start_and_wait: DVM

**Review by FlorentDev64 — APPROVED** [review]
LGTM

**Comment by clemencebic** [comment]
@cstenac @apichery do you want to also review the PR before we merge?

**Comment by apichery** [comment]
Superseded by https://github.com/dataiku/dip/pull/18174

**Pull request closed without merging**
