### PR TITLE
Deploy anywhere feature

### PR DESCRIPTION
**Pull request by michaelbourhis**
Python API part of the deploy anywhere feature: https://github.com/dataiku/dip/pull/14733
Adds a handler to the API node admin client to create code envs in the global cache of an API node.

See [ch75547](https://app.shortcut.com/dataiku/story/75547/base-docker-image-for-vertex-ai-prediction).

### CODE REVIEW

**Review by lpenet — APPROVED** [review]
LGTM+Tested.

**Comment by alarive** [comment]
LGTM+tested

**Review by alarive — APPROVED** [review]

**Comment by lpenet** [comment]
See companion dip PR for an explanation of changes in latest commit.

**Review by lpenet — APPROVED** [review]
LGTM+Full retested with last changes on a GCP VM.

**Pull request merged**
