### PR TITLE
Added a function to retrieve a model from a comparison

### PR DESCRIPTION
**Pull request by pmmayne**
An integration test is going to be submitted shortly after this PR is merged.

At the moment, the integration test cannot run because of PythonContextSwitcher issues. However, the draft PR can be read at this location:

https://github.com/dataiku/dip/pull/14501

### CODE REVIEW

**Review by lpenet — CHANGES_REQUESTED** [review]
I would be much more conservative there as we are, for instance, in the JS code of the frontend. In the frontend, items are retrieved through our internal API and we can have some expectations on what we test.

Here, we offer an API to a user who can be either a skilled person, or someone randomly using whatever comes at hand.

So, I would use regular expressions and perform full matches. You will find the regex in `FullModelId` and `FullModelEvaluationId`.

I would also raise an exception when no match is found.

I do not think that the `get_comparable` name is adequate. It is meaningful only in the context of MES/MC. Here, we are adding a method to DSSProject I am not the best at naming, but something like `get_from_full_id` reads better to me. Do not hesitate to make a counter-proposal.

**Comment by pmmayne** [comment]
@lpenet you're right and I will add the regex check 

For the renaming, I would suggest `get_model_from_full_id` because what we retrieve is a model (either lab model from analysis, saved model from the flow or a model evaluation from a MES). What's your opinion?

**Comment by michaelbourhis** [comment]
Agreed with @lpenet remarks, and I'm not the best to find name, but I like the one proposed by @pmmayne : we are in the Project context, it's good to add some meaning of what we can retrieve with the method.

**Comment by pmmayne** [comment]
@lpenet I added the pattern matching and changed the name.

However, as I said before, because the API must be usable with Python 2, I cannot use `re.fullmatch` and therefore I decided to add a `\Z` to the regex ensuring that the regex is matching the input String exactly.

In the Integration Test PR, I added tests on the event that a user tries to `get_from_full_id` something that is not the full id of a smv, a lab model or a me.

**Review by michaelbourhis — APPROVED** [review]
LGTM

**Review by lpenet — APPROVED** [review]
LGTM+Tested

**Pull request merged**
